erDiagram

    USERS {
        number id
        string name
        string email
        string password
    }

    USER_GIFTS {
        number GIF_ID
        string ALIAS
        number USER_ID
    }

    REQUESTS {
        number USER_ID
        string SERVICE
        json REQUEST_BODY
        number HTTP_STATUS
        json RESPONSE_BODY
        string REQUEST_IP
    }


    USERS ||--o{ USER_GIFTS : owns

    USERS ||--o{ REQUESTS : "made requests"
